reference: /home/users/data/01_reference/human_g1k_v37/human_g1k_v37.fasta

# basic languages
java: /home/users/cjyoon/anaconda3/bin/java
python3: /home/users/cjyoon/anaconda3/bin/python
python2: /home/users/cjyoon/anaconda3/envs/py27/bin/python

# bam processing
picard: /home/users/tools/picard/dist/picard.jar
gatk: /home/users/cjyoon/tools/GenomeAnalysisTK-3.8-1/GenomeAnalysisTK.jar
samtools: /home/users/cjyoon/anaconda3/bin/samtools
bwa: /home/users/cjyoon/anaconda3/bin/bwa
knownindel: /home/users/data/02_annotation/01_GATK/01_golden_standard/Mills_and_1000G_gold_standard.indels.b37.vcf
dbSnp: /home/users/data/02_annotation/01_GATK/02_db_snp/dbsnp_138.b37.vcf

# snv variant callers

# sv variant callers

# cnv variant callers

# variant filters