samples:
    test:
        tumor_fastq: dna_fastq/testT_r
        normal_fastq: dna_fastq/testN_r
        sex: XX
    sample1:
        tumor_fastq: dna_fastq/sampleT_r
        normal_fastq: dna_fastq/sampleN_r
        sex: XY
#    3796:
#        tumor_fastq: dna_fastq/3796_T_r
#        normal_fastq: dna_fastq/3796_N_r
#        sex: XX
